services:
  
  db: 
    image: postgres:17.2
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=smartscript
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    
  server:
    build: ./server
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=root
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "8080:80"
    env_file:
      - ./client/.env
    depends_on:
      - server
    

volumes:
  db-data:
  
    
